/**
 * Validation for student records and their academic enrollment.
 *
 * The same schemas run in the browser (instant feedback) and on the server
 * (the real check). Nothing here mentions a specific class, division or
 * program — those are database records chosen by their id, so a new program
 * such as "I.Com" works without touching this file.
 */
import { z } from 'zod'
import { cnic, isoDate, optionalText, phone, requiredText, uuid } from './common'

export const STUDENT_STATUSES = [
  'ACTIVE',
  'INACTIVE',
  'LEFT',
  'GRADUATED',
  'TRANSFERRED_OUT',
] as const

/** How each status reads in the interface. */
export const STUDENT_STATUS_LABEL: Record<(typeof STUDENT_STATUSES)[number], string> = {
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  LEFT: 'Left / Withdrawn',
  GRADUATED: 'Graduated',
  TRANSFERRED_OUT: 'Transferred out',
}

export const ENROLLMENT_STATUS_LABEL: Record<string, string> = {
  ACTIVE: 'Current',
  TRANSFERRED: 'Transferred',
  PROMOTED: 'Promoted',
  REPEATED: 'Repeated',
  COMPLETED: 'Completed',
  LEFT: 'Left',
}

/** Optional CNIC / B-Form: either a properly formatted number, or nothing. */
const optionalCnic = z
  .union([cnic, z.literal('')])
  .optional()
  .transform((value) => (value === '' ? undefined : value))

/** Optional Pakistani phone number. */
const optionalPhone = z
  .union([phone, z.literal('')])
  .optional()
  .transform((value) => (value === '' ? undefined : value))

const optionalIsoDate = z
  .union([isoDate, z.literal('')])
  .optional()
  .transform((value) => (value === '' ? undefined : value))

/* -------------------------------------------------------------------------- */
/* The student's own details                                                  */
/* -------------------------------------------------------------------------- */

const studentDetailsShape = {
  // Personal
  fullName: requiredText(120, 'Student name'),
  dateOfBirth: optionalIsoDate,
  gender: z.union([z.enum(['MALE', 'FEMALE', 'OTHER']), z.literal('')]).optional()
    .transform((v) => (v === '' ? undefined : v)),
  phone: optionalPhone,
  email: z.union([z.email('Enter a valid email address.'), z.literal('')]).optional()
    .transform((v) => (v === '' ? undefined : v)),
  address: optionalText(500),
  city: optionalText(80),
  cnicBformNumber: optionalCnic,

  // Guardian
  fatherName: requiredText(120, "Father's name"),
  fatherCnic: optionalCnic,
  fatherPhone: optionalPhone,
  fatherOccupation: optionalText(100),
  motherName: optionalText(120),
  guardianName: optionalText(120),
  guardianRelation: optionalText(50),
  guardianPhone: optionalPhone,

  // Previous education
  previousInstitution: optionalText(200),
  previousResultSummary: optionalText(200),
  previousResultObtained: z.coerce.number().int().min(0).max(10000).optional(),
  previousResultTotal: z.coerce.number().int().min(1).max(10000).optional(),
  matricRollNumber: optionalText(30),
  matricBoard: optionalText(100),

  notes: optionalText(2000),
}

/* -------------------------------------------------------------------------- */
/* Academic enrollment                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Where the student sits.
 *
 * Only the section is stored — the section already knows its academic group,
 * and the group knows the class, division and program. The class/division/
 * program ids are sent too so the server can confirm the section really is the
 * one the administrator picked in the form.
 */
export const enrollmentSelectionSchema = z.object({
  academicSessionId: uuid,
  classId: uuid,
  divisionId: uuid,
  programId: uuid,
  sectionId: uuid,
  rollNumber: z
    .string()
    .trim()
    .max(20, 'Use at most 20 characters.')
    .regex(/^[A-Za-z0-9-]*$/, 'Roll number may contain letters, numbers and hyphens only.')
    .transform((v) => (v === '' ? undefined : v))
    .optional(),
})

export type EnrollmentSelection = z.infer<typeof enrollmentSelectionSchema>

/* -------------------------------------------------------------------------- */
/* Create / update                                                            */
/* -------------------------------------------------------------------------- */

export const studentCreateSchema = z
  .object({
    ...studentDetailsShape,

    // Admission. The student ID is generated by the server, never sent by the
    // browser; the admission number may be supplied or auto-generated.
    admissionNumber: z
      .string()
      .trim()
      .max(30, 'Use at most 30 characters.')
      .transform((v) => (v === '' ? undefined : v))
      .optional(),
    admissionDate: isoDate,

    enrollment: enrollmentSelectionSchema,

    /** Optionally create a student portal login at the same time. */
    createAccount: z.boolean().default(false),
    username: z
      .string()
      .trim()
      .max(50)
      .transform((v) => (v === '' ? undefined : v.toLowerCase()))
      .optional(),
  })
  .refine(
    (data) =>
      data.previousResultObtained === undefined ||
      data.previousResultTotal === undefined ||
      data.previousResultObtained <= data.previousResultTotal,
    { message: 'Marks obtained cannot be more than the total.', path: ['previousResultObtained'] },
  )
  .refine((data) => !data.createAccount || (data.username?.length ?? 0) >= 3, {
    message: 'Enter a username of at least 3 characters for the portal account.',
    path: ['username'],
  })
  .refine(
    (data) => !data.username || /^[A-Za-z0-9._-]+$/.test(data.username),
    {
      message: 'Use letters, numbers, dots, underscores and hyphens only — no spaces.',
      path: ['username'],
    },
  )

export type StudentCreateInput = z.infer<typeof studentCreateSchema>

/** Editing the student's own details. Enrollment is changed separately. */
export const studentUpdateSchema = z
  .object({
    ...studentDetailsShape,
    admissionNumber: requiredText(30, 'Admission number'),
    admissionDate: isoDate,
  })
  .refine(
    (data) =>
      data.previousResultObtained === undefined ||
      data.previousResultTotal === undefined ||
      data.previousResultObtained <= data.previousResultTotal,
    { message: 'Marks obtained cannot be more than the total.', path: ['previousResultObtained'] },
  )

export type StudentUpdateInput = z.infer<typeof studentUpdateSchema>

export const studentStatusSchema = z.object({
  status: z.enum(STUDENT_STATUSES),
  reason: optionalText(255),
})

/* -------------------------------------------------------------------------- */
/* Moving a student                                                           */
/* -------------------------------------------------------------------------- */

/**
 * A move inside the CURRENT session — a different section, program or division.
 * The old enrollment row is closed as TRANSFERRED and a new one opened, so both
 * remain in the student's history.
 */
export const studentTransferSchema = z.object({
  enrollment: enrollmentSelectionSchema,
  reason: optionalText(255),
})

export type StudentTransferInput = z.infer<typeof studentTransferSchema>

/**
 * A move into a LATER session — the new academic year.
 * `outcome` records why the previous year ended.
 */
export const studentPromoteSchema = z.object({
  enrollment: enrollmentSelectionSchema,
  outcome: z.enum(['PROMOTED', 'REPEATED', 'COMPLETED']).default('PROMOTED'),
  reason: optionalText(255),
})

export type StudentPromoteInput = z.infer<typeof studentPromoteSchema>

/* -------------------------------------------------------------------------- */
/* Portal account                                                             */
/* -------------------------------------------------------------------------- */

export const studentAccountSchema = z
  .object({
    /** Link an account that already exists… */
    userId: uuid.optional(),
    /** …or create a new one with this username. */
    username: z
      .string()
      .trim()
      .min(3, 'Use at least 3 characters.')
      .max(50, 'Use at most 50 characters.')
      .regex(/^[A-Za-z0-9._-]+$/, 'Use letters, numbers, dots, underscores and hyphens only.')
      .transform((v) => v.toLowerCase())
      .optional(),
  })
  .refine((data) => Boolean(data.userId) !== Boolean(data.username), {
    message: 'Either choose an existing account or enter a username for a new one.',
    path: ['username'],
  })

export type StudentAccountInput = z.infer<typeof studentAccountSchema>

/* -------------------------------------------------------------------------- */
/* List query                                                                 */
/* -------------------------------------------------------------------------- */

export const studentListQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(5).max(100).default(25),
  search: z.string().trim().max(100).optional(),

  // Every academic filter is an id, so new programs and sections work with no
  // code change.
  sessionId: z.union([uuid, z.literal('')]).optional().transform((v) => (v === '' ? undefined : v)),
  classId: z.union([uuid, z.literal('')]).optional().transform((v) => (v === '' ? undefined : v)),
  divisionId: z.union([uuid, z.literal('')]).optional().transform((v) => (v === '' ? undefined : v)),
  programId: z.union([uuid, z.literal('')]).optional().transform((v) => (v === '' ? undefined : v)),
  sectionId: z.union([uuid, z.literal('')]).optional().transform((v) => (v === '' ? undefined : v)),

  status: z.union([z.enum(STUDENT_STATUSES), z.literal('ALL')]).default('ACTIVE'),
  sort: z.enum(['fullName', 'studentCode', 'admissionNumber', 'admissionDate', 'createdAt']).default('fullName'),
  direction: z.enum(['asc', 'desc']).default('asc'),
})

export type StudentListQuery = z.infer<typeof studentListQuerySchema>
